---
title: Overview
order: 10
layout: page
---

[[guide.overview]]
= Guides

These guides give an introduction to Vaadin Platform and gives instructions for installing development tools and creating a Vaadin project.
It also covers upgrading from earlier Vaadin versions, as well as deploying to production, which you may want to set up in your workflow.

<<intro/overview#, Introduction>>::
Gives an introduction to Vaadin and its two frameworks: Flow for server-side Java and Fusion for client-side TypeScript with Java server-side integrations.

<<start/install#, Installing Development Tools>>::
Gives instructions for installing development tools for developing Vaadin applications.

<<start/project#, Starting a Vaadin Project>>::
Gives instructions for creating a new Vaadin project and how to import it in an IDE.
Instructions are for Maven and also for Gradle projects.

<<start/workflow#, Development Workflow>>::
Gives instructions for setting up smooth development workflow.
This involves setting up live reload to show changes to application immediately in the browser.
You can also set up the application to run on a development server instead of using Spring Boot or an embedded server.

<<starter/overview#, Starter Applications>>::
The starter applications are fully functional business applications that utilize the Vaadin commercial add-ons.

<<upgrading/overview#, Upgrading Guide>>::
How to upgrade from Vaadin 8 or 10-13 to the Vaadin 14 LTS, and further to the latest release.

<<production/overview#, Deploying to Production>>::
Gives instructions for deploying to a production server or cloud.
You should also enable the production mode, which optimizes the compilation for building more efficient versions of various resources.
